#==============================================================================
test_infile_parser.jl — FORTRAN `.infile` parser tests.

Exercises:
  - header line capture (NLINES + verbatim text)
  - free-format numeric reads with inline `->` annotation stripping
  - trailing-column tolerance
  - conditional flag reads
  - ISMOOTH-in-IPROFL decimal encoding
  - sediment block (IPROFL=1 branch)
  - field-mode wave/SWL interpolation
  - bathymetry section
  - strict-validation rejection of Phase-2-deferred flags
  - round-trip with run_simulation!
==============================================================================#

using Test
using CSHORE
using CSHORE: read_infile, _tokenize_infile, _next_int, _next_float, _next_iprofl

const FIXTURES = joinpath(@__DIR__, "fixtures")
const REAL_FIXTURE = "/Users/rdchlntc/Documents/GitHub/cshore-permafrost/examples/output/debug_runs/1_waves_thawed_smooth/infile"

@testset "infile parser" begin

    @testset "tokenizer" begin
        t = _tokenize_infile(joinpath(FIXTURES, "simple.infile"))

        # Header parsed verbatim (simple.infile has NLINES=2)
        @test length(t.header) == 2
        @test occursin("Simple CSHORE test fixture", t.header[1])
        @test occursin("Generated by", t.header[2])

        # Inline annotations stripped: first body token is "1" (ILINE),
        # not "->ILINE" or anything else.
        @test _next_int(t) == 1
        @test _next_int(t) == 0   # IPROFL
        @test _next_int(t) == 0   # IPERM
    end

    @testset "IPROFL decimal encoding (ISMOOTH)" begin
        # The FORTRAN IPROFL can be "1.0" (iprofl=1, ismooth=1) or
        # "1.1" (iprofl=1, ismooth=0). We test by constructing synthetic
        # token streams.
        t1 = CSHORE.InfileTokens(String[], ["1.0"], 1, false)
        ip, sm = _next_iprofl(t1)
        @test ip == 1
        @test sm == 1

        t2 = CSHORE.InfileTokens(String[], ["1.1"], 1, false)
        ip, sm = _next_iprofl(t2)
        @test ip == 1
        @test sm == 0

        t3 = CSHORE.InfileTokens(String[], ["0"], 1, false)
        ip, sm = _next_iprofl(t3)
        @test ip == 0
    end

    @testset "simple.infile (fixed bed IPROFL=0)" begin
        cfg = read_infile(joinpath(FIXTURES, "simple.infile"))

        # Flags
        @test cfg.options.iprofl == 0
        @test cfg.options.iline == 1
        @test cfg.options.iperm == 0
        @test cfg.options.iover == 0
        @test cfg.options.iveg == 0
        @test cfg.options.isedav == 0    # not read when IPROFL=0

        # Physical params
        @test cfg.grid.dx == 1.0
        @test cfg.gamma == 0.78

        # Wave time series (field mode: NWAVE=1 → 2 rows)
        @test length(cfg.boundary.timebc) == 2
        @test cfg.boundary.timebc ≈ [0.0, 3600.0]
        @test cfg.boundary.tpbc ≈ [8.0, 8.0]
        @test cfg.boundary.hrmsbc ≈ [1.0, 1.0]
        @test cfg.boundary.wangbc ≈ [0.0, 0.0]
        @test cfg.boundary.swlbc ≈ [0.0, 0.0]

        # Bathymetry
        @test cfg.bathymetry.nbinp[1] == 11
        @test cfg.bathymetry.xbinp[1, 1] == 0.0
        @test cfg.bathymetry.xbinp[11, 1] == 10.0
        @test cfg.bathymetry.zbinp[1, 1] ≈ -5.0
        @test cfg.bathymetry.zbinp[11, 1] ≈ 2.0
        # fbinp is segment-wise: FBINP(J-1) for J=2..NBINP
        @test cfg.bathymetry.fbinp[1, 1] ≈ 0.002
        @test cfg.bathymetry.fbinp[10, 1] ≈ 0.002
    end

    @testset "morph.infile (IPROFL=1)" begin
        cfg = read_infile(joinpath(FIXTURES, "morph.infile"))
        @test cfg.options.iprofl == 1
        @test cfg.options.isedav == 0   # explicitly set in the file after IPROFL

        # Sediment block
        @test cfg.sediment.d50 ≈ 0.3e-3 atol=1e-9    # 0.3 mm → 0.0003 m
        @test cfg.sediment.sg == 2.65
        @test cfg.sediment.tanphi == 0.63
        @test cfg.sediment.blp == 0.002
        @test cfg.sediment.effb == 0.005
        @test cfg.sediment.efff == 0.01
        @test cfg.sediment.slp == 0.2

        # 4 BC windows (NWAVE=3 → NWAVE+1=4 rows in field mode)
        @test length(cfg.boundary.timebc) == 4
        @test cfg.boundary.timebc[end] ≈ 10800.0
    end

    @testset "end-to-end round trip (simple fixture)" begin
        cfg = read_infile(joinpath(FIXTURES, "simple.infile"))
        state = run_simulation!(cfg)
        jmax = state.jmax[1]
        # Fixed bed should preserve initial bathymetry exactly
        @test state.zb[1, 1] ≈ -5.0
        @test state.zb[jmax, 1] ≈ 2.0
        # Wave field evolved (Hrms=1m imposed at offshore boundary)
        @test state.hrms[1] ≈ 1.0
        # Some nonzero wave response in the interior
        @test any(state.hrms[2:jmax-1] .> 0)
    end

    @testset "end-to-end round trip (morph fixture)" begin
        cfg = read_infile(joinpath(FIXTURES, "morph.infile"))
        state = run_simulation!(cfg)
        # Should have completed to the end time (3 hours)
        @test state.time ≈ 10800.0 atol=1e-6
        # All bed elevations should be finite (no NaN / runaway)
        jmax = state.jmax[1]
        @test all(isfinite, view(state.zb, 1:jmax, 1))
        # Within sensible physical bounds for an 11-point 10-meter domain
        @test minimum(view(state.zb, 1:jmax, 1)) > -20.0
        @test maximum(view(state.zb, 1:jmax, 1)) < 10.0
        # Max |dzb| shouldn't exceed the bed-change limiter summed over
        # sub-steps — realistic bound is a few meters over 3 hours
        # with this tiny domain.
        @test state.zb[1, 1] >= -15.0
    end

    @testset "NetCDF + .infile integration" begin
        tmp = joinpath(mktempdir(), "infile_roundtrip.nc")
        cfg = read_infile(joinpath(FIXTURES, "simple.infile"))
        run_simulation!(cfg; outdir=dirname(tmp), outfile=basename(tmp))
        @test isfile(tmp)
        # Quick content check: x coord and zb are populated
        using NCDatasets
        NCDataset(tmp, "r") do ds
            @test Int(ds.dim["x"]) == 11
            @test Int(ds.dim["time"]) == 2
            @test ds["zb"][1, 1] ≈ -5.0
            @test ds["zb"][end, 1] ≈ 2.0
        end
    end

    @testset "strict validation: Phase-2-deferred rejection" begin
        # The real-world fixture has IOVER=1 (now supported) but may have
        # other unsupported features (IPERM, IROLL, etc.). The parser should
        # either succeed or fail with a clear message about a still-deferred feature.
        if isfile(REAL_FIXTURE)
            err = try
                read_infile(REAL_FIXTURE)
                nothing
            catch e
                e
            end
            # IOVER=1 is now supported, so the fixture may parse successfully
            # or fail on another deferred feature. Either is acceptable.
            if err !== nothing
                @test err isa ArgumentError || err isa ErrorException
            else
                @test true  # parsing succeeded
            end
        else
            @info "Real fixture not available; skipping" path=REAL_FIXTURE
        end
    end

    @testset "error on missing file" begin
        err = try
            read_infile("/tmp/nonexistent_$(rand(UInt)).infile")
            nothing
        catch e
            e
        end
        @test err isa ArgumentError
        @test occursin("not found", err.msg)
    end
end
